### ISSUE TITLE
Is there any way I can get workflow status

### ISSUE THREAD

**Issue by mxnoob** [hatchet-dev/hatchet#1071]
I tried to get with `await hatchet.rest.aio.workflow_get(workflow_id)`

<details> <summary>Error</summary>
> Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/router.py", line 28, in test_back_task
    res = await hatchet.rest.aio.workflow_get(workflow_id)
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest_client.py", line 117, in workflow_get
    return await self.workflow_api.workflow_get(
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 33, in wrapper_function
    return await wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api/workflow_api.py", line 702, in workflow_get
    response_data = await self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api_client.py", line 262, in call_api
    response_data = await self.rest_client.request(
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/rest.py", line 180, in request
    r = await pool_manager.request(**args)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 622, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: /api/v1/workflows/0d19625e-7c4c-4358-9304-1f1498df3dda
</details>

**Comment by abelanger5** [comment]
Hey @mxnoob, I think you're looking for `workflow_run_get`. For example: 

```py
run = hatchet.admin.run_workflow("MyWorkflow", {})
await run.result()

workflow_run = await hatchet.rest.aio.workflow_run_get(run.workflow_run_id)

# can now access workflow_run.status
```

**Comment by mxnoob** [comment]
Hi @abelanger5, thanks for the reply, I have rewritten the code and am getting the error again. I am trying to get data from another docker compose, could this be the cause?

```py
@router.get("/workflow/{workflow_id}")
async def test_back_task(workflow_id: str):
    res = await hatchet.rest.aio.workflow_run_get(workflow_id)
    return {"workflow_status": res.status}
```
<details> <summary>Error</summary>
> Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/router.py", line 31, in test_back_task
    res = await hatchet.rest.aio.workflow_run_get(workflow_id)
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest_client.py", line 159, in workflow_run_get
    return await self.workflow_api.workflow_run_get(
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 33, in wrapper_function
    return await wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api/workflow_api.py", line 1842, in workflow_run_get
    response_data = await self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api_client.py", line 262, in call_api
    response_data = await self.rest_client.request(
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/rest.py", line 180, in request
    r = await pool_manager.request(**args)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 622, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: /api/v1/tenants/707d0855-80ab-4e1f-a156-f1c4546cbf52/workflow-runs/b0a0d8b0-5338-40f2-a0d9-471c8db22ee7
</details>

**Comment by abelanger5** [comment]
Hey @mxnoob how are you instantiating the Hatchet client? This looks like potentially a configuration issue or a bug on our end -- it may be that when you overwrite the `hostPort` value in the config, it's unsetting the URL for the API server. But checking how you're initializing the Hatchet client would be helpful.

**Comment by mxnoob** [comment]
<details><summary>.env</summary>
HATCHET_CLIENT_TOKEN=token

HATCHET_CLIENT_TLS_STRATEGY=none
HATCHET_CLIENT_HOST_PORT=host.docker.internal:7077
</details>

I got docker-compose.yml from https://docs.hatchet.run/self-hosting/docker-compose

What settings did I miss?

**Comment by abelanger5** [comment]
Got it, I believe this is a bug on our end -- when you use the `HATCHET_CLIENT_HOST_PORT` variable, we are no longer setting the API server URL. As a quick fix, could you do the following:

1. In the `setup-config` service, set the following env vars:
    ```
    SERVER_GRPC_BROADCAST_ADDRESS=host.docker.internal:7077
    SERVER_URL=http://host.docker.internal:8080
    ```

    Then restart the docker compose services. 
2. Regenerate an API token, and use the new token. 
3. Remove `HATCHET_CLIENT_HOST_PORT` from the .env file. 

Let me know if that works while we investigate this.

**Comment by mxnoob** [comment]
I did everything according to the points, unfortunately to no avail
In `setup-config` I set `SERVER_GRPC_BROADCAST_ADDRESS` and `GRPC_BROADCAST_ADDRESS`

<details><summary>error</summary>
INFO:     172.23.0.1:40706 - "GET /workflow/ef1d4bf8-be2c-4ea5-a786-28604ff0b5f9 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1109, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 123, in start_connection
    raise OSError(first_errno, msg)
ConnectionRefusedError: [Errno 111] Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/router.py", line 29, in test_back_task
    res = await hatchet.rest.aio.workflow_run_get(workflow_id)
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest_client.py", line 159, in workflow_run_get
    return await self.workflow_api.workflow_run_get(
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 33, in wrapper_function
    return await wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api/workflow_api.py", line 1842, in workflow_run_get
    response_data = await self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api_client.py", line 262, in call_api
    response_data = await self.rest_client.request(
  File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/rest.py", line 180, in request
    r = await pool_manager.request(**args)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1124, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)]
</details>

**Comment by abelanger5** [comment]
@mxnoob could you try one more step -- setting `SERVER_URL` in the `setup-config` step to the value `http://host.docker.internal:8080`, restart and regenerate the API token again. 

And you are correct, it should be `SERVER_GRPC_BROADCAST_ADDRESS`, nice catch.

**Comment by mxnoob** [comment]
@abelanger5 thanks! I got a new error, now pydantic

>    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
        result = await app(  # type: ignore[func-returns-value]
      File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
        return await self.app(scope, receive, send)
      File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
        await super().__call__(scope, receive, send)
      File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
        await self.middleware_stack(scope, receive, send)
      File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
        raise exc
      File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
        await self.app(scope, receive, _send)
      File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
        await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
      File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
        raise exc
      File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
        await app(scope, receive, sender)
      File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
        await self.middleware_stack(scope, receive, send)
      File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
        await route.handle(scope, receive, send)
      File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
        await self.app(scope, receive, send)
      File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
        await wrap_app_handling_exceptions(app, request)(scope, receive, send)
      File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
        raise exc
      File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
        await app(scope, receive, sender)
      File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
        response = await f(request)
      File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
        raw_response = await run_endpoint_function(
      File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
        return await dependant.call(**values)
      File "/app/router.py", line 29, in test_back_task
        res = await hatchet.rest.aio.workflow_run_get(workflow_id)
      File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest_client.py", line 159, in workflow_run_get
        return await self.workflow_api.workflow_run_get(
      File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 33, in wrapper_function
        return await wrapper(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api/workflow_api.py", line 1846, in workflow_run_get
        return self.api_client.response_deserialize(
      File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api_client.py", line 316, in response_deserialize
        return_data = self.deserialize(
      File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api_client.py", line 415, in deserialize
        return self.__deserialize(data, response_type)
      File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api_client.py", line 460, in __deserialize
        return self.__deserialize_model(data, klass)
      File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/api_client.py", line 746, in __deserialize_model
        return klass.from_dict(data)
      File "/usr/local/lib/python3.10/site-packages/hatchet_sdk/clients/rest/models/workflow_run.py", line 144, in from_dict
        return cls.model_validate(obj)
      File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 627, in model_validate
        return cls.__pydantic_validator__.validate_python(
    pydantic_core._pydantic_core.ValidationError: 1 validation error for WorkflowRun
  Input should be a valid dictionary or instance of WorkflowRun [type=model_type, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type

**Comment by abelanger5** [comment]
@mxnoob just to double check, which version of the Python SDK are you using?

**Comment by mxnoob** [comment]
> @mxnoob just to double check, which version of the Python SDK are you using?

hatchet-sdk 0.38.3

**Comment by hatchet-temporary** [comment]
hey @mxnoob - what's the code you're running that triggers this error? is it still what you put in [this earlier comment](https://github.com/hatchet-dev/hatchet/issues/1071#issuecomment-2500104295)? If yes, I'll try to reproduce this!

**Comment by mxnoob** [comment]
Hi @hatchet-temporary, that's right, the error occurs when this code is called

**Comment by hatchet-temporary** [comment]
Hey @mxnoob - looking into this a bit more! One thing I'm noticing is in the code, it looks like you're passing a `workflow_id` to `workflow_run_get`, which takes a workflow _run_ id as its parameter. I just wanted to make sure that the value you're passing is, in fact, a run id! (One note is I think this will cause a 500 if you pass an id that doesn't exist, so I think you're likely all good on this front 👍)

To me, this looks like it's likely a bug in an old version of the SDK. The TL;DR of what's going on is that somehow, an empty string is being passed to a Pydantic `model_validate`, which is then failing. In reality, `model_validate` should _never_ be called on a string, which I think is likely a bug on our side.

Would it be possible to upgrade the version of the SDK on your end and see if the issue persists? If it does, it's pretty likely it'd be a straightforward fix I could push!

**Comment by AISG-Alvin** [comment]
Unfortunately, i'm facing the same validation error despite using the latest sdk (1.7.0)

Logs:
API ERROR: Failed to get status from Hatchet for workflow run f19947b4-d902-43e0-bf23-9f0c2a2b7b38 (course_id 1): 1 validation error for V1TaskSummary
workflowRunExternalId
Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.11/v/string_type
Traceback (most recent call last):
  File "/app/src/api/routers/workflow.py", line 151, in get_status
    status_info = await hatchet.runs.aio_get(workflow_run_id)
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/features/runs.py", line 130, in aio_get
    return await asyncio.to_thread(self.get, workflow_run_id)
  File "/usr/local/lib/python3.13/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/features/runs.py", line 121, in get
    return self._wra(client).v1_workflow_run_get(str(workflow_run_id))
  File "/app/.venv/lib/python3.13/site-packages/pydantic/_internal/_validate_call.py", line 39, in wrapper_function
    return wrapper(*args, **kwargs)
  File "/app/.venv/lib/python3.13/site-packages/pydantic/_internal/_validate_call.py", line 136, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/clients/rest/api/workflow_runs_api.py", line 713, in v1_workflow_run_get
    return self.api_client.response_deserialize(
        response_data=response_data,
        response_types_map=_response_types_map,
    ).data
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/clients/rest/api_client.py", line 314, in response_deserialize
    return_data = self.deserialize(
        response_text, response_type, content_type
    )
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/clients/rest/api_client.py", line 430, in deserialize
    return self.__deserialize(data, response_type)
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/clients/rest/api_client.py", line 475, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/clients/rest/api_client.py", line 770, in __deserialize_model
    return klass.from_dict(data)
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/clients/rest/models/v1_workflow_run_details.py", line 139, in from_dict
    [V1TaskSummary.from_dict(_item) for _item in obj["tasks"]]
  File "/app/.venv/lib/python3.13/site-packages/hatchet_sdk/clients/rest/models/v1_task_summary.py", line 191, in from_dict
    _obj = cls.model_validate(
        {
        ...<32 lines>...
        }
    )
  File "/app/.venv/lib/python3.13/site-packages/pydantic/main.py", line 703, in model_validate
    return cls.__pydantic_validator__.validate_python(
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
    )
pydantic_core._pydantic_core.ValidationError: 1 validation error for V1TaskSummary
workflowRunExternalId
Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]

**Comment by mrkaye97** [comment]
hi @AISG-Alvin - you'll need to pull the most recent API / dashboard + engine (or hatchet-lite) images, which should fix this

**Comment by AISG-Alvin** [comment]
hi @mrkaye97 , thanks for the prompt reply! Yes, i managed to resolve this after pulling the latest images. Thanks again for the help!
