### ISSUE TITLE
bug(engine): grpc_broadcast_address hatchet-engine

### ISSUE THREAD

**Issue by Jak2k** [hatchet-dev/hatchet#264]
This gets logged when starting the worker script:

```
🪓 [INFO/HatchetClient] Initialized HatchetClient
(node:21382) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/jak2k/Projects/news-analysis/downloader/node_modules/@hatchet-dev/typescript-sdk/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: Name resolution failed for target dns:hatchet-engine:7070
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: Name resolution failed for target dns:hatchet-engine:7070
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: Name resolution failed for target dns:hatchet-engine:7070
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: Name resolution failed for target dns:hatchet-engine:7070
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: Name resolution failed for target dns:hatchet-engine:7070
/home/jak2k/Projects/news-analysis/downloader/node_modules/.pnpm/@hatchet-dev+typescript-sdk@0.1.27/node_modules/@hatchet-dev/typescript-sdk/clients/worker/worker.js:86
                throw new hatchet_error_1.default(`Could not register workflow: ${e.message}`);
                      ^

HatchetError: Could not register workflow: /WorkflowService/PutWorkflow UNAVAILABLE: Name resolution failed for target dns:hatchet-engine:7070
    at Worker.<anonymous> (/home/jak2k/Projects/news-analysis/downloader/node_modules/.pnpm/@hatchet-dev+typescript-sdk@0.1.27/node_modules/@hatchet-dev/typescript-sdk/clients/worker/worker.js:86:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/jak2k/Projects/news-analysis/downloader/node_modules/.pnpm/@hatchet-dev+typescript-sdk@0.1.27/node_modules/@hatchet-dev/typescript-sdk/clients/worker/worker.js:6:65)

Node.js v20.10.0
```

**Comment by abelanger5** [comment]
Hey @Jak2k, which `docker-compose` file did you use to get the Hatchet instance running? I'm asking because I see `target dns:hatchet-engine:7070`, but our `docker-compose` files are setting a broadcast address of `localhost:7077` in our examples.

**Comment by Jak2k** [comment]
I copy-pasted the docker-compose from the [example-repo](https://github.com/hatchet-dev/hatchet-typescript-quickstart).

**Comment by grutt** [comment]
Hi @Jak2k, the `hatchet-engine` hostname is only available within the Docker network created by docker-compose. When you access the service from your local machine/terminal, you need to use `localhost` instead.

Are you setting the `HATCHET_CLIENT_HOSTPORT` environment variable? This should not be needed.

**Comment by Jak2k** [comment]
I only set the token, just like the quickstart's README told.

**Comment by grutt** [comment]
🤔 Would you be able to decode the token (JWT) and send the payload?

**Comment by Jak2k** [comment]
```
{
  "aud": "http://localhost:8080",
  "exp": 1718134560,
  "grpc_broadcast_address": "hatchet-engine:7070",
  "iat": 1710358560,
  "iss": "http://localhost:8080",
  "server_url": "http://localhost:8080",
  "sub": "707d0855-80ab-4e1f-a156-f1c4546cbf52",
  "token_id": "f3ca7be5-876e-49c6-9a17-709be65e37a1"
}
```

**Comment by Jak2k** [comment]
Is there any quickfix I can do?

**Comment by Jak2k** [comment]
The payload is now different:
```json
{
  "aud": "http://localhost:8080",
  "exp": 1720025319,
  "grpc_broadcast_address": "localhost:7077",
  "iat": 1712249319,
  "iss": "http://localhost:8080",
  "server_url": "http://localhost:8080",
  "sub": "707d0855-80ab-4e1f-a156-f1c4546cbf52",
  "token_id": "a508aa56-99a9-4e25-a07a-3402a1a64cb3"
}
```

The error is the same:
```
🪓 [INFO/HatchetClient] Initialized HatchetClient
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: No connection established. Last error: 40586AA0477F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
 (2024-04-04T16:52:42.825Z)
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: No connection established. Last error: 40586AA0477F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
 (2024-04-04T16:52:42.825Z)
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: No connection established. Last error: 40586AA0477F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
 (2024-04-04T16:52:42.825Z)
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: No connection established. Last error: 40586AA0477F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
 (2024-04-04T16:52:42.825Z)
🪓 [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: No connection established. Last error: 40586AA0477F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
 (2024-04-04T16:52:42.825Z)
/home/jak2k/Projects/news-analysis/downloader/node_modules/.pnpm/@hatchet-dev+typescript-sdk@0.4.0/node_modules/@hatchet-dev/typescript-sdk/clients/worker/worker.js:97
                throw new hatchet_error_1.default(`Could not register workflow: ${e.message}`);
                      ^

HatchetError: Could not register workflow: /WorkflowService/PutWorkflow UNAVAILABLE: No connection established. Last error: 40586AA0477F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
 (2024-04-04T16:52:42.825Z)
    at Worker.<anonymous> (/home/jak2k/Projects/news-analysis/downloader/node_modules/.pnpm/@hatchet-dev+typescript-sdk@0.4.0/node_modules/@hatchet-dev/typescript-sdk/clients/worker/worker.js:97:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/jak2k/Projects/news-analysis/downloader/node_modules/.pnpm/@hatchet-dev+typescript-sdk@0.4.0/node_modules/@hatchet-dev/typescript-sdk/clients/worker/worker.js:6:65)

Node.js v21.7.1
```

**Comment by Jak2k** [comment]
With `HATCHET_CLIENT_TLS_STRATEGY=none` in `.env` it works, but I now get this:
```
🪓 [ERROR/ActionListener] Failed to send heartbeat: /Dispatcher/Heartbeat UNIMPLEMENTED: unknown method Heartbeat for service Dispatcher
E Connection to dns:localhost:7077 at ::1:7077 rejected by server because of excess pings. Increasing ping interval to 20000 ms
🪓 [INFO/ActionListener] Connecting to Hatchet to establish listener for actions... 0/5 (last attempt: 1712249697929)
```

**Comment by abelanger5** [comment]
@Jak2k the log `🪓 [INFO/ActionListener] Connecting to Hatchet to establish listener for actions... 0/5 (last attempt: 1712249697929)` is a sign that it's working - you should be able to trigger a workflow. 

The `/Dispatcher/Heartbeat UNIMPLEMENTED` error is a sign that you're on the wrong engine version, you'll need to repull the Hatchet images again and restart with docker-compose.

**Comment by grutt** [comment]
@Jak2k have you been able to resolve this issue?
Going to close for now, but we can re open if needed.

**Comment by platform-kit** [comment]
@grutt I am following the hatchet-lite example from the docs, and getting this same error.

**Comment by dougwithseismic** [comment]
hatchet-lite docs examples are outdated (client as named export etc) so I don't trust this.

**Comment by dougwithseismic** [comment]
Fresh load from hatchet-lite docs and similar story. Seems docs in general need updating (hatchet client isn't default export etc). 

```
🪓 25000 | 03/23/25, 08:53:04 PM  [ERROR/Admin] Error: /WorkflowService/PutWorkflow UNAVAILABLE: No connection established. Last error: Error: 88660000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:
```

**Comment by grutt** [comment]
very large doc refresh on the way #1361 ... 
@dougwithseismic looks like you'll need to set the env var `HATCHET_CLIENT_TLS_STRATEGY=none`
