### ISSUE TITLE
React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by giubaru** [hatchet-dev/hatchet#360]
Hello! I'm having this issue everytime I want to execute a workflow:

I'm running the server with Docker Compose as it's explained in the self-hosting docs.

Basically when I ran the workflow and this fails, I get this screen and exception:
```
Unexpected Application Error!
React.Children.only expected to receive a single React element child.
Error: React.Children.only expected to receive a single React element child.
    at Object.only (http://localhost:8080/assets/index-DnlpGlhe.js:15:3958)
    at http://localhost:8080/assets/utils-LoSfO6Rg.js:1:1313
    at Hf (http://localhost:8080/assets/index-DnlpGlhe.js:44:19519)
    at Jp (http://localhost:8080/assets/index-DnlpGlhe.js:46:1571)
    at g_ (http://localhost:8080/assets/index-DnlpGlhe.js:46:45934)
    at h_ (http://localhost:8080/assets/index-DnlpGlhe.js:46:39727)
    at T1 (http://localhost:8080/assets/index-DnlpGlhe.js:46:39655)
    at Wl (http://localhost:8080/assets/index-DnlpGlhe.js:46:39508)
    at Cd (http://localhost:8080/assets/index-DnlpGlhe.js:46:35875)
    at c_ (http://localhost:8080/assets/index-DnlpGlhe.js:46:34826)
```
![image](https://github.com/hatchet-dev/hatchet/assets/39471667/3029fcb4-c204-495f-bb61-fbd23e88b677)

![image](https://github.com/hatchet-dev/hatchet/assets/39471667/a0d3dfd4-7ec8-4c39-b1a5-9896e3682bb9)

**Comment by giubaru** [comment]
I saw it's fixed in the version `v0.19.3`!
