### ISSUE TITLE
Quickstart issues

### ISSUE THREAD

**Issue by leosunmo** [hatchet-dev/hatchet#47]
Just started going through the Quickstart page on a fresh setup and encountering some issues.

While going through the CLI setup on https://docs.hatchet.run/getting-started/setup/quickstart/#creating-your-first-module, I made a mistake when running the `config set-address` command and wrote `https` instead of `http`. This worked without any errors, so perhaps some validation would be good there. I know that it will validate once you run `hatchet init`, but maybe an earlier check is worth it.

---
Another issue I encountered is that the Team I set up during the registration phase wasn't actually set up properly. I didn't notice that and ran through the Quickstart commands (with the incorrect `https` address):

```
cd smoke-test
hatchet config set-address https://localhost:8080
hatchet config set-api-token $token
```
The return of the `set-api-token` command did not include a default team (I only noticed later):
```
$ hatchet config set-api-token '$token'
Set the current api token successfully
Set the current organization as 6145face-98c9-4566-b0a6-582caf6cfe69
```

When I then run `hatchet init` it results in: 
```
$ hatchet init
team id must be set: run [hatchet config set-team]
```
Running `hatchet config set-team` then results in an index out of range panic.
```
$ hatchet config set-team
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/hatchet-dev/hatchet/cmd/hatchet-cli/cli.glob..func5(0x2154c60?, {0x22d8920?, 0x0?, 0x0?})
	/home/runner/work/hatchet/hatchet/cmd/hatchet-cli/cli/config.go:68 +0xda
github.com/spf13/cobra.(*Command).execute(0x2154c60, {0x22d8920, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2153840)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/hatchet-dev/hatchet/cmd/hatchet-cli/cli.Execute()
	/home/runner/work/hatchet/hatchet/cmd/hatchet-cli/cli/root.go:38 +0x7f
main.main()
	/home/runner/work/hatchet/hatchet/cmd/hatchet-cli/main.go:8 +0x17
```

When I later to go check on my teams in the UI it's empty, despite having created an initial team in the registering phase. So perhaps there's an issue creating the initial team? 
After creating a team on the http://localhost:8080/organization/teams page, it no longer paniced when I ran `hatchet init`. It timed out since I had incorrectly configured the hatchet URL, but after changing the URL it worked fine.

It was hard to figure out what I needed to do to fix it, so I ended up deleting the `~/.hatchet/hatchet.yaml` file and start over.

It looks like if I just run `hatchet config set-api-token` again it will fetch the team correctly the second time, _but it uses the Hatchet URL from the JWT token_, so even if the URL is incorrect, you won't know because the `hatchet config set-api-token` successfully fetches your Org and Team.

The URL in the token should either be used to populate the URL in the `~/.hatchet/hatchet.yaml` file or it should at least throw a warning if it detects that they differ. Maybe use the `~/.hatchet/hatchet.yaml` URL when looking up Org/Team and ignore the JWT URL?

**Comment by abelanger5** [comment]
Thanks for the report @leosunmo! Working through these issues this week, will keep you updated. Some comments:

> Running `hatchet config set-team` then results in an index out of range panic.

The `hatchet config set-team` command should require 1 argument, with the team ID. I'll push a quick PR to enforce this. 

> When I later to go check on my teams in the UI it's empty, despite having created an initial team in the registering phase. So perhaps there's an issue creating the initial team?

This might be because Temporal can't be reached, which can leave the team in a bit of a dirty state, as a new namespace in Temporal is created for the team. 

> It looks like if I just run hatchet config set-api-token again it will fetch the team correctly the second time, but it uses the Hatchet URL from the JWT token, so even if the URL is incorrect, you won't know because the hatchet config set-api-token successfully fetches your Org and Team.

`hatchet config set-api-token` should also require an argument, so I'm not quite sure what's going on here.  With regards to using the URL from the JWT token - that definitely isn't expected behavior, so I'll take a closer look.
