### ISSUE TITLE
SSL error: Failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:7

### ISSUE THREAD

**Issue by simjak** [hatchet-dev/hatchet#474]
I am running from docker-compose.yml and got this error while trying to run the worker:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "src/worker/main.py", line 5, in start
    worker.register_workflow(ProcessingWorkflow())  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "hatchet_sdk/worker.py", line 347, in register_workflow
    self.client.admin.put_workflow(workflow.get_name(), workflow.get_create_opts())
  File "hatchet_sdk/clients/admin.py", line 69, in put_workflow
    raise ValueError(f"Could not put workflow: {e}")
ValueError: Could not put workflow: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:7077: Ssl handshake failed: SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"
    debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-05-09T14:28:34.759853+03:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:7077: Ssl handshake failed: SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"}"
   ```

**Comment by simjak** [comment]
solved:
```
HATCHET_CLIENT_TLS_STRATEGY="none"
```
