### ISSUE TITLE
[Bug] Request message serialization failure on Node.js v22

### ISSUE THREAD

**Issue by vavido** [hatchet-dev/hatchet#910]
Since switching to Node.js 22, my hatchet worker is unable to connect to my local hatchet-lite instance. 
The same code works on v20.

Error message:
```
Failed to initialize Hatchet HatchetError: Could not register workflow: /WorkflowService/PutWorkflow INTERNAL: Request message serialization failure: "length" is outside of buffer bounds
     at Worker.<anonymous> (node_modules/.pnpm/@hatchet-dev+typescript-sdk@0.10.1/node_modules/@hatchet-dev/typescript-sdk/clients/worker/worker.js:146:23)
     at Generator.throw (<anonymous>)
     at rejected (node_modules/.pnpm/@hatchet-dev+typescript-sdk@0.10.1/node_modules/@hatchet-dev/typescript-sdk/clients/worker/worker.js:6:65)
```

**Comment by abelanger5** [comment]
Hi @vavido, we'll be working on tackling compatibility issues on the Typescript SDK next week. Thanks for flagging this!
